symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # lifetime: 3600    # Durée de validité du lien (en secondes)
    throttle_limit: 0   # Délai entre 2 requetes de reset (en secondes), à eviter en prod
